// THIS IS AN AUTOGENERATED FILE, PLEASE EDIT alerts_offroad.json
QT_TRANSLATE_NOOP("OffroadAlert", R"(Device temperature too high. System cooling down before starting. Current internal component temperature: %1)");
QT_TRANSLATE_NOOP("OffroadAlert", R"(Immediately connect to the internet to check for updates. If you do not connect to the internet, openpilot won't engage in %1)");
QT_TRANSLATE_NOOP("OffroadAlert", R"(Connect to internet to check for updates. openpilot won't automatically start until it connects to internet to check for updates.)");
QT_TRANSLATE_NOOP("OffroadAlert", R"(Unable to download updates
%1)");
QT_TRANSLATE_NOOP("OffroadAlert", R"(Taking camera snapshots. System won't start until finished.)");
QT_TRANSLATE_NOOP("OffroadAlert", R"(An update to your device's operating system is downloading in the background. You will be prompted to update when it's ready to install.)");
QT_TRANSLATE_NOOP("OffroadAlert", R"(Failed to register with comma.ai backend. It will not connect or upload to comma.ai servers, and receives no support from comma.ai. If this is a device purchased at comma.ai/shop, open a ticket at https://comma.ai/support.)");
QT_TRANSLATE_NOOP("OffroadAlert", R"(openpilot was unable to identify your car. Your car is either unsupported or its ECUs are not recognized. Please submit a pull request to add the firmware versions to the proper vehicle. Need help? Join discord.comma.ai.)");
QT_TRANSLATE_NOOP("OffroadAlert", R"(openpilot detected a change in the device's mounting position. Ensure the device is fully seated in the mount and the mount is firmly secured to the windshield.)");
QT_TRANSLATE_NOOP("OffroadAlert", R"(Poor visibility detected for driver monitoring. Ensure the device has a clear view of the driver. This can be checked in the device settings. Extreme lighting conditions and/or unconventional mounting positions may also trigger this alert.)");
QT_TRANSLATE_NOOP("OffroadAlert", R"(Excessive %1 actuation detected on your last drive. Please contact support at https://comma.ai/support and share your device's Dongle ID for troubleshooting.)");
